require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HolidaysController do

  # This should return the minimal set of attributes required to create a valid
  # Holiday. As you add validations to Holiday, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all holidays as @holidays" do
      holiday = Holiday.create! valid_attributes
      get :index
      assigns(:holidays).should eq([holiday])
    end
  end

  describe "GET show" do
    it "assigns the requested holiday as @holiday" do
      holiday = Holiday.create! valid_attributes
      get :show, :id => holiday.id
      assigns(:holiday).should eq(holiday)
    end
  end

  describe "GET new" do
    it "assigns a new holiday as @holiday" do
      get :new
      assigns(:holiday).should be_a_new(Holiday)
    end
  end

  describe "GET edit" do
    it "assigns the requested holiday as @holiday" do
      holiday = Holiday.create! valid_attributes
      get :edit, :id => holiday.id
      assigns(:holiday).should eq(holiday)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Holiday" do
        expect {
          post :create, :holiday => valid_attributes
        }.to change(Holiday, :count).by(1)
      end

      it "assigns a newly created holiday as @holiday" do
        post :create, :holiday => valid_attributes
        assigns(:holiday).should be_a(Holiday)
        assigns(:holiday).should be_persisted
      end

      it "redirects to the created holiday" do
        post :create, :holiday => valid_attributes
        response.should redirect_to(Holiday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved holiday as @holiday" do
        # Trigger the behavior that occurs when invalid params are submitted
        Holiday.any_instance.stub(:save).and_return(false)
        post :create, :holiday => {}
        assigns(:holiday).should be_a_new(Holiday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Holiday.any_instance.stub(:save).and_return(false)
        post :create, :holiday => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested holiday" do
        holiday = Holiday.create! valid_attributes
        # Assuming there are no other holidays in the database, this
        # specifies that the Holiday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Holiday.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => holiday.id, :holiday => {'these' => 'params'}
      end

      it "assigns the requested holiday as @holiday" do
        holiday = Holiday.create! valid_attributes
        put :update, :id => holiday.id, :holiday => valid_attributes
        assigns(:holiday).should eq(holiday)
      end

      it "redirects to the holiday" do
        holiday = Holiday.create! valid_attributes
        put :update, :id => holiday.id, :holiday => valid_attributes
        response.should redirect_to(holiday)
      end
    end

    describe "with invalid params" do
      it "assigns the holiday as @holiday" do
        holiday = Holiday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Holiday.any_instance.stub(:save).and_return(false)
        put :update, :id => holiday.id, :holiday => {}
        assigns(:holiday).should eq(holiday)
      end

      it "re-renders the 'edit' template" do
        holiday = Holiday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Holiday.any_instance.stub(:save).and_return(false)
        put :update, :id => holiday.id, :holiday => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested holiday" do
      holiday = Holiday.create! valid_attributes
      expect {
        delete :destroy, :id => holiday.id
      }.to change(Holiday, :count).by(-1)
    end

    it "redirects to the holidays list" do
      holiday = Holiday.create! valid_attributes
      delete :destroy, :id => holiday.id
      response.should redirect_to(holidays_url)
    end
  end

end
